name: CI

on:
  push:
    branches: [ ci/setup ]
  pull_request:
    branches: [ ci/setup ]

env:
  ACTIONS_STEP_DEBUG: true

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate script syntax
        id: validate
        run: |
          if ! bash -n status-check.sh; then
            echo "::error::Script validation failed"
            exit 1
          fi
      - name: Create job summary
        run: |
          echo "## Validation Summary" >> $GITHUB_STEP_SUMMARY
          echo "* Runner OS: ${{ runner.os }}" >> $GITHUB_STEP_SUMMARY
          echo "* Branch: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "* Script validation: ✅ Passed" >> $GITHUB_STEP_SUMMARY

  test:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        id: tests
        run: |
          echo "::warning::Running in test mode - results may not reflect production environment"
          echo "Running tests"
          if [ $RANDOM -gt 16383 ]; then
            echo "::warning::Some tests took longer than expected"
          fi
          exit 0
      - name: Create job summary
        run: |
          echo "## Test Summary" >> $GITHUB_STEP_SUMMARY
          echo "* Environment: ${{ runner.os }} / ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "* Test execution: ✅ Completed" >> $GITHUB_STEP_SUMMARY

  package:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create report
        run: |
          echo "Report..." > report.txt
          zip report.zip report.txt
      - name: Upload artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: report.zip
      - name: Create job summary
        run: |
          echo "## Package Summary" >> $GITHUB_STEP_SUMMARY
          echo "* Environment: ${{ runner.os }} / ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "* Artifact: [Download Report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})" >> $GITHUB_STEP_SUMMARY 