name: CI

on:
  push:
    branches: [ ci/setup ]
  pull_request:
    branches: [ ci/setup ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate script syntax
        run: bash -n status-check.sh

  test:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: |
          echo "Running tests"
          exit 0

  package:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create report
        run: |
          echo "Report..." > report.txt
          zip report.zip report.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: report.zip 